config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }

  namespace :learners do
    resources :dashboard, only: [:index]
    resources :courses, only: [:show, :index]
    resources :lessons, only: [:show]
    resources :quizzes, only: [:show, :index] do
      collection do
        get 'level', to: 'quizzes#level'
        post '/:id', to: 'quizzes#submit_quiz_answer', as: 'submit_quiz_answer'
      end
    end
  end

  namespace :instructors do
    resources :dashboard, only: [:index]
    resources :courses
    resources :lessons do
      resources :sub_titles, only: [:create, :destroy, :update]
      resources :images, only: [:create, :destroy, :update]
      resources :descriptions, only: [:create, :destroy, :update]
    end
    resources :quizzes
    resources :blogs
  end

  # Define API routes for blogs
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :blogs, only: [:index, :show]
      # Add more API endpoints as needed
    end
  end

end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :instructor, class_name: 'User'

  validates :description, presence: true
  validates :title, presence: true, uniqueness: { scope: :instructor_id }
  validates :instructor_id, presence: true

  has_rich_text :description

  def trix_description
    description.body.to_s if description.present?
  end
end

app/controllers/api/v1/blogs_controller.rb
# app/controllers/api/v1/blogs_controller.rb
module Api
  module V1
    class BlogsController < ApplicationController
      before_action :set_blog, only: [:show]

      # GET /api/v1/blogs
      def index
        @blogs = Blog.all
        render json: @blogs.as_json(only: [:id, :title, :created_at], methods: [:trix_description])
      end

      # GET /api/v1/blogs/:id
      def show
        render json: @blog.as_json(methods: [:trix_description])
      end

      private

      def set_blog
        @blog = Blog.find(params[:id])
      end
    end
  end
end

app/controllers/instructors/blogs_controller.rb
class Instructors::BlogsController < InstructorBaseController
  before_action :authenticate_user!
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = current_instructor.blogs
  end

  def show
  end

  def new
    @blog = current_instructor.blogs.build
  end

  def edit
  end

  def create
    @blog = current_instructor.blogs.build(blog_params)
    puts "==================#{@blog.inspect}"
    puts "==================#{@blog.save}"
    if @blog.save
      redirect_to instructors_blog_path(@blog), notice: 'blog was successfully created.'
    else
      flash.now[:alert] = 'There was an error creating the blog.'
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to instructors_blog_path(@blog), notice: 'blog was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating the blog.'
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to instructors_blogs_path, notice: 'blog was successfully destroyed.'
  end

  def preview
  end


  private

  def set_blog
    @blog = current_instructor.blogs.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :description)
  end
end

app/controllers/instructors/courses_controller.rb
# app/controllers/instructors/courses_controller.rb
class Instructors::CoursesController < InstructorBaseController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = current_instructor.courses
  end

  def show
  end

  def new
    @course = current_instructor.courses.build
  end

  def edit
  end

  def create
    @course = current_instructor.courses.build(course_params)

    if @course.save
      redirect_to instructors_course_path(@course), notice: 'Course was successfully created.'
    else
      flash.now[:alert] = 'There was an error creating the course.'
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to instructors_course_path(@course), notice: 'Course was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating the course.'
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to instructors_courses_path, notice: 'Course was successfully destroyed.'
  end

  private

  def set_course
    @course = current_instructor.courses.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description)
  end
end

  

app/controllers/instructors/dashboard_controller.rb
class Instructors::DashboardController < InstructorBaseController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/instructors/descriptions_controller.rb
module Instructors
  class DescriptionsController < InstructorBaseController
    before_action :authenticate_user!
    before_action :set_lesson
    before_action :authorize_instructor
    before_action :set_description, only: [:update, :destroy]

    def create
      @description = @lesson.descriptions.new(description_params)
      @description.instructor_id = current_user.id  # Assign the current user's ID as instructor_id
      if @description.save
        redirect_to instructors_lesson_path(@lesson), notice: 'Description was successfully created.'
      else
        redirect_to instructors_lesson_path(@lesson)
      end
    end

    def update
      if @description.update(description_params)
        redirect_to instructors_lesson_path(@lesson), notice: 'Description was successfully updated.'
      else
        render 'instructors/lessons/show'
      end
    end

    def destroy
      @description.destroy
      redirect_to instructors_lesson_path(@lesson), notice: 'Description was successfully deleted.'
    end

    private

    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def authorize_instructor
      unless @lesson.course.instructor_id == current_user.id
        redirect_to instructors_lessons_path, alert: 'You are not authorized to perform this action.'
      end
    end

    def set_description
      @description = @lesson.descriptions.find(params[:id])
    end

    def description_params
      params.require(:description).permit(:value, :priority)
    end
  end
end

app/controllers/instructors/images_controller.rb
module Instructors
  class ImagesController < InstructorBaseController
    before_action :authenticate_user!
    before_action :set_lesson
    before_action :authorize_instructor
    before_action :set_image, only: [:update, :destroy]

    def create
      @image = @lesson.images.new(image_params)
      @image.instructor_id = current_user.id  # Assign the current user's ID as instructor_id
      if @image.save
        redirect_to instructors_lesson_path(@lesson), notice: 'Image was successfully created.'
      else
        redirect_to instructors_lesson_path(@lesson)
      end
    end

    def update
      if @image.update(image_params)
        redirect_to instructors_lesson_path(@lesson), notice: 'Image was successfully updated.'
      else
        render 'instructors/lessons/show'
      end
    end

    def destroy
      @image.destroy
      redirect_to instructors_lesson_path(@lesson), notice: 'Image was successfully deleted.'
    end

    private

    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def authorize_instructor
      unless @lesson.course.instructor_id == current_user.id
        redirect_to instructors_lessons_path, alert: 'You are not authorized to perform this action.'
      end
    end

    def set_image
      @image = @lesson.images.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:value, :priority)
    end
  end
end

app/controllers/instructors/lessons_controller.rb
class Instructors::LessonsController < InstructorBaseController
  before_action :authenticate_user!
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = current_instructor.lessons
  end

  def show
    @sub_title = @lesson.sub_titles.build
    @description = @lesson.descriptions.build
    @image = @lesson.images.build
    @combined_contents = @lesson.combined_contents
  end

  def new
    @lesson = current_instructor.lessons.build
  end

  def edit
  end

  def create
    @lesson = current_instructor.lessons.build(lesson_params)

    if @lesson.save
      redirect_to instructors_lesson_path(@lesson), notice: 'Lesson was successfully created.'
    else
      flash.now[:alert] = 'There was an error creating the lesson.'
      render :new
    end
  end

  def update
    if @lesson.update(lesson_params)
      redirect_to instructors_lesson_path(@lesson), notice: 'Lesson was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating the lesson.'
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    redirect_to instructors_lessons_path, notice: 'Lesson was successfully destroyed.'
  end

  def preview
  end


  private

  def set_lesson
    @lesson = current_instructor.lessons.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :priority, :course_id)
  end
end

app/controllers/instructors/quizzes_controller.rb
class Instructors::QuizzesController < InstructorBaseController
    before_action :authenticate_user!
    before_action :set_quiz, only: [:edit, :update, :destroy]
  
    def index
      @courses = current_instructor.courses
    end
  
    def show
      @course = Course.find_by_id(params[:id])
      @quizzes = @course.quizzes
    end
  
    def new
      @quiz = current_instructor.quizzes.build
    end
  
    def edit
    end
  
    def create
      @quiz = current_instructor.quizzes.build(quiz_params)
        
      if @quiz.save
        redirect_to instructors_quiz_path(@quiz.course), notice: 'Quiz was successfully created.'
      else
        flash.now[:alert] = 'There was an error creating the quiz.'
        render :new
      end
    end
  
    def update
      if @quiz.update(quiz_params)
        redirect_to instructors_quiz_path(@quiz.course), notice: 'Quiz was successfully updated.'
      else
        flash.now[:alert] = 'There was an error updating the quiz.'
        render :edit
      end
    end
  
    def destroy
      @quiz.destroy
      redirect_to instructors_quizzes_path, notice: 'Quiz was successfully destroyed.'
    end
  
    private
  
    def set_quiz
      @quiz = current_instructor.quizzes.find(params[:id])
    end
  
    def quiz_params
      params.require(:quiz).permit(:question, :lesson_id, :answer1, :answer2, :answer3, :answer4, :right_answer, :level)
    end
  end
  

app/controllers/instructors/sub_titles_controller.rb
module Instructors
  class SubTitlesController < InstructorBaseController
    before_action :authenticate_user!
    before_action :set_lesson
    before_action :authorize_instructor
    before_action :set_sub_title, only: [:update, :destroy]

    def create
      @sub_title = @lesson.sub_titles.new(sub_title_params)
      @sub_title.instructor_id = current_user.id  # Assign the current user's ID as instructor_id
      if @sub_title.save
        redirect_to instructors_lesson_path(@lesson), notice: 'Subtitle was successfully created.'
      else
        redirect_to instructors_lesson_path(@lesson)
      end
    end

    def update
      if @sub_title.update(sub_title_params)
        redirect_to instructors_lesson_path(@lesson), notice: 'Subtitle was successfully updated.'
      else
        render 'instructors/lessons/show'
      end
    end

    def destroy
      @sub_title.destroy
      redirect_to instructors_lesson_path(@lesson), notice: 'Subtitle was successfully deleted.'
    end

    private

    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def authorize_instructor
      unless @lesson.course.instructor_id == current_user.id
        redirect_to instructors_lessons_path, alert: 'You are not authorized to perform this action.'
      end
    end

    def set_sub_title
      @sub_title = @lesson.sub_titles.find(params[:id])
    end

    def sub_title_params
      params.require(:sub_title).permit(:value, :priority)
    end
  end
end

app/helpers/api/v1/blogs_helper.rb
module Api::V1::BlogsHelper
end

app/helpers/instructors/courses_helper.rb
module Instructors::CoursesHelper
end

app/helpers/instructors/descriptions_helper.rb
module Instructors::DescriptionsHelper
end

app/helpers/instructors/images_helper.rb
module Instructors::ImagesHelper
end

app/helpers/instructors/quizzes_helper.rb
module Instructors::QuizzesHelper
end

app/helpers/instructors/sub_titles_helper.rb
module Instructors::SubTitlesHelper
end

app/views/instructors/blogs/_form.html.erb
<!-- app/views/instructors/blogs/_form.html.erb -->
<div class="max-w-4xl mx-auto px-4 py-8">
  <%= form_with(model: @blog, url: @blog.persisted? ? instructors_blog_path(@blog) : instructors_blogs_path, method: @blog.persisted? ? :patch : :post, data: { turbo: false }, class: "bg-gradient-to-r from-white to-gray-100 shadow-2xl rounded-xl px-10 pt-8 pb-10 mb-6") do |form| %>

    <!-- Error Messages -->
    <% if @blog.errors.any? %>
      <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-6 rounded-lg">
        <div class="flex">
          <div class="flex-shrink-0">
            <i class="fas fa-exclamation-circle text-red-500"></i>
          </div>
          <div class="ml-3">
            <h3 class="text-lg font-bold">There were some errors:</h3>
            <ul class="mt-2 list-disc pl-5 space-y-1">
              <% @blog.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <div class="mb-8">
      <div class="flex items-center mb-2">
        <i class="fas fa-heading text-gray-400 mr-2 text-xl"></i>
        <%= form.label :title, class: "block text-gray-700 text-lg font-semibold" %>
      </div>
      <%= form.text_field :title, placeholder: "Enter blog title", class: "shadow-md appearance-none border rounded-lg w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-2 focus:ring-blue-500" %>
    </div>


    <div class="mb-8">
      <div class="flex items-center mb-2">
        <i class="fas fa-align-left text-gray-400 mr-2 text-xl"></i>
        <%= form.label :description, class: "block text-gray-700 text-lg font-semibold" %>
      </div>
      <%= form.rich_text_area :description,
        class: "shadow-md appearance-none border rounded-lg w-full min-h-[10rem] max-h-[30rem] py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-2 focus:ring-blue-500",
        data: {
          controller: "trix",
          direct_upload_url: Rails.application.routes.url_helpers.rails_direct_uploads_path,
          direct_upload_token: @blog.persisted? ? @blog.signed_id : nil
        }, placeholder: "Enter blog description" %>
    </div>
    


    <div class="flex items-center justify-between mb-6">
      <%= form.button :submit, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-lg focus:outline-none focus:shadow-outline transition duration-300 ease-in-out transform hover:-translate-y-1 flex items-center" do %>
        <i class="fas fa-check-circle mr-2 text-lg"></i>
        <span><%= @blog.persisted? ? "Update Blog" : "Create Blog" %></span>
      <% end %>
    
      <%= link_to instructors_blogs_path, class: "flex items-center border border-gray-300 text-gray-700 text-sm font-bold py-3 px-6 rounded-lg hover:bg-gray-200 focus:outline-none focus:shadow-outline transition duration-300 ease-in-out transform hover:-translate-y-1", 'data-turbo': false do %>
        <i class="fas fa-arrow-left fa-fw mr-2 text-lg"></i>
        <span>Back</span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/instructors/blogs/edit.html.erb
<!-- app/views/instructors/blogs/edit.html.erb -->
<div class="container mx-auto p-8">
  <div class="flex justify-between items-center mb-8">
    <div>
      <h1 class="text-4xl font-bold text-teal-600 mb-4">Edit Blog</h1>
      <p class="text-gray-700 text-lg">Update or create new blogs with ease.</p>
    </div>
    <div>
      <%= link_to new_instructors_blog_path, class: "bg-gradient-to-r from-teal-500 to-blue-500 hover:from-teal-600 hover:to-blue-600 text-white font-bold py-2 px-6 rounded-lg shadow-lg transition duration-300 flex items-center" do %>
        <i class="fas fa-plus-circle fa-fw text-lg mr-2"></i>
        Add Blog
      <% end %>
    </div>
  </div>

  <hr class="my-8 border-gray-300 border-2">

  <%= render 'form' %>
</div>

app/views/instructors/blogs/index.html.erb
<!-- app/views/instructors/blogs/index.html.erb -->
<div class="container mx-auto p-8">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-4xl font-bold text-teal-600">Your Blogs</h1>
    <%= link_to new_instructors_blog_path, class: "bg-gradient-to-r from-teal-500 to-blue-500 hover:from-teal-600 hover:to-blue-600 text-white font-bold py-2 px-6 rounded-lg shadow-lg transition duration-300 flex items-center" do %>
      <i class="fas fa-plus-circle fa-fw text-lg mr-2"></i>
      Add Blog
    <% end %>
  </div>

  <hr class="my-8 border-gray-300 border-2">

  <% if @blogs.any? %>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <% @blogs.each do |blog| %>
        <div class="bg-white shadow-lg rounded-lg overflow-hidden transform hover:scale-105 transition duration-300 relative">
          <%= link_to instructors_blog_path(blog), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "absolute top-2 right-2 text-red-600 hover:text-red-800 focus:outline-none" do %>
            <i class="fas fa-times-circle fa-lg"></i>
          <% end %>

          <div class="p-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-4">
              <%= link_to blog.title, instructors_blog_path(blog), class: "hover:underline" %>
            </h2>
            <p class="text-gray-600">Instructor: <%= blog.instructor.name %></p>
          </div>

          <div class="bg-gradient-to-r from-teal-500 to-blue-500 px-6 py-4 flex justify-between items-center">
            <%= link_to edit_instructors_blog_path(blog), class: "text-white bg-blue-600 hover:bg-blue-800 px-4 py-2 rounded focus:outline-none focus:shadow-outline transition duration-300" do %>
              <i class="fas fa-edit fa-fw mr-2"></i> Edit Blog
            <% end %>
            <%= link_to instructors_blog_path(blog), class: "text-white bg-teal-600 hover:bg-teal-800 px-4 py-2 rounded focus:outline-none focus:shadow-outline transition duration-300" do %>
              <i class="fas fa-eye fa-fw mr-2"></i> View Blog
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-700 text-center mt-12">No records found.</p>
  <% end %>
</div>

app/views/instructors/blogs/new.html.erb
<!-- app/views/instructors/blogs/new.html.erb -->
<div class="container mx-auto p-8">
  <div class="mb-8">
    <div class="flex justify-between items-center">
      <div>
        <h1 class="text-4xl font-bold text-teal-600 mb-4">New Blog</h1>
        <p class="text-gray-700 text-lg">Create a new blog with the details below.</p>
      </div>
      <div>
        <%= link_to instructors_blogs_path, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-6 rounded-lg shadow-lg transition duration-300 flex items-center" do %>
          <i class="fas fa-arrow-left fa-fw text-lg mr-2"></i>
          Back
        <% end %>
      </div>
    </div>
  </div>

  <hr class="my-8 border-gray-300 border-2">

  <%= render 'form' %>
</div>

app/views/instructors/blogs/show.html.erb
<!-- Main container -->
<div class="container mx-auto px-4 py-8">
  <!-- Blog Details Card -->
  <div class="bg-white shadow-md rounded-lg overflow-hidden relative">
    <!-- Delete Button -->
    <div class="absolute top-0 right-0 mt-4 mr-4 delete-blog">
      <%= link_to instructors_blog_path(@blog), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "text-gray-400 hover:text-red-600 focus:outline-none" do %>
        <i class="fas fa-times-circle fa-lg"></i>
      <% end %>
    </div>
    
    <!-- Blog Details -->
    <div class="p-6">
      <h1 class="text-3xl font-bold text-gray-800 mb-4"><%= @blog.title %></h1>
      <p class="text-lg text-gray-700 mb-6">Created At: <%= @blog.created_at.strftime('%B %d, %Y') %></p>
      <!-- Adjust as per your blog model structure -->
    </div>
    
    <!-- Action Buttons -->
    <div class="bg-gradient-to-r from-teal-500 to-blue-500 px-6 py-4 flex justify-between">
      <%= link_to edit_instructors_blog_path(@blog), class: "text-white bg-green-500 hover:bg-green-700 px-4 py-2 rounded focus:outline-none focus:shadow-outline flex items-center" do %>
        <i class="fas fa-edit fa-fw mr-2"></i> Edit Blog
      <% end %>
      <%= link_to instructors_blogs_path, class: "text-white bg-gray-500 hover:bg-gray-700 px-4 py-2 rounded focus:outline-none focus:shadow-outline flex items-center" do %>
        <i class="fas fa-arrow-left fa-fw mr-2"></i> Back
      <% end %>
    </div>
  </div>
</div>