config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }

  namespace :learners do
    resources :dashboard, only: [:index]
    resources :courses, only: [:show, :index]
    resources :lessons, only: [:show]
    resources :quizzes, only: [:show, :index] do
      collection do
        get 'level', to: 'quizzes#level'
        post '/:id', to: 'quizzes#submit_quiz_answer', as: 'submit_quiz_answer'
      end
    end
  end

  namespace :instructors do
    resources :dashboard, only: [:index]
    resources :courses
    resources :lessons do
      resources :sub_titles, only: [:create, :destroy, :update]
      resources :images, only: [:create, :destroy, :update]
      resources :descriptions, only: [:create, :destroy, :update]
    end
    resources :quizzes
    resources :blogs
  end

  # Define API routes for blogs
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :blogs, only: [:index, :show]
      # Add more API endpoints as needed
    end
  end

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  belongs_to :instructor, class_name: 'User'
  has_many :sub_titles, -> { order(:priority) }, dependent: :destroy
  has_many :descriptions, -> { order(:priority) }, dependent: :destroy
  has_many :images, -> { order(:priority) }, dependent: :destroy
  has_many :quiz, dependent: :destroy

  validates :course_id, presence: true
  validates :title, presence: true, uniqueness: { scope: :course_id }
  validates :priority, presence: true, numericality: { only_integer: true, greater_than: 0 }, uniqueness: { scope: :course_id }
  validates :instructor_id, presence: true

  validate :priority_must_be_unique_within_course

  def combined_contents
    combined = []

    # Fetch all subtitles, descriptions, and images associated with this lesson
    subtitles = sub_titles.to_a.select(&:persisted?)
    descriptions = self.descriptions.to_a.select(&:persisted?)
    images = self.images.to_a.select(&:persisted?)

    combined += subtitles
    combined += descriptions
    combined += images

    # Sort combined array by priority
    combined.sort_by! { |item| item.priority }

    combined
  end

  private

  def priority_must_be_unique_within_course
    if course.lessons.where(priority: priority).exists? && (new_record? || changed.include?('priority'))
      errors.add(:priority, "must be unique within the course")
    end
  end
end

app/controllers/instructors/blogs_controller.rb
class Instructors::BlogsController < InstructorBaseController
  before_action :authenticate_user!
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = current_instructor.blogs
  end

  def show
  end

  def new
    @blog = current_instructor.blogs.build
  end

  def edit
  end

  def create
    @blog = current_instructor.blogs.build(blog_params)
    puts "==================#{@blog.inspect}"
    puts "==================#{@blog.save}"
    if @blog.save
      redirect_to instructors_blog_path(@blog), notice: 'blog was successfully created.'
    else
      flash.now[:alert] = 'There was an error creating the blog.'
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to instructors_blog_path(@blog), notice: 'blog was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating the blog.'
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to instructors_blogs_path, notice: 'blog was successfully destroyed.'
  end

  def preview
  end


  private

  def set_blog
    @blog = current_instructor.blogs.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :description)
  end
end

app/controllers/instructors/courses_controller.rb
# app/controllers/instructors/courses_controller.rb
class Instructors::CoursesController < InstructorBaseController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = current_instructor.courses
  end

  def show
  end

  def new
    @course = current_instructor.courses.build
  end

  def edit
  end

  def create
    @course = current_instructor.courses.build(course_params)

    if @course.save
      redirect_to instructors_course_path(@course), notice: 'Course was successfully created.'
    else
      flash.now[:alert] = 'There was an error creating the course.'
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to instructors_course_path(@course), notice: 'Course was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating the course.'
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to instructors_courses_path, notice: 'Course was successfully destroyed.'
  end

  private

  def set_course
    @course = current_instructor.courses.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description)
  end
end

  

app/controllers/instructors/dashboard_controller.rb
class Instructors::DashboardController < InstructorBaseController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/instructors/descriptions_controller.rb
module Instructors
  class DescriptionsController < InstructorBaseController
    before_action :authenticate_user!
    before_action :set_lesson
    before_action :authorize_instructor
    before_action :set_description, only: [:update, :destroy]

    def create
      @description = @lesson.descriptions.new(description_params)
      @description.instructor_id = current_user.id  # Assign the current user's ID as instructor_id
      if @description.save
        redirect_to instructors_lesson_path(@lesson), notice: 'Description was successfully created.'
      else
        redirect_to instructors_lesson_path(@lesson)
      end
    end

    def update
      if @description.update(description_params)
        redirect_to instructors_lesson_path(@lesson), notice: 'Description was successfully updated.'
      else
        render 'instructors/lessons/show'
      end
    end

    def destroy
      @description.destroy
      redirect_to instructors_lesson_path(@lesson), notice: 'Description was successfully deleted.'
    end

    private

    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def authorize_instructor
      unless @lesson.course.instructor_id == current_user.id
        redirect_to instructors_lessons_path, alert: 'You are not authorized to perform this action.'
      end
    end

    def set_description
      @description = @lesson.descriptions.find(params[:id])
    end

    def description_params
      params.require(:description).permit(:value, :priority)
    end
  end
end

app/controllers/instructors/images_controller.rb
module Instructors
  class ImagesController < InstructorBaseController
    before_action :authenticate_user!
    before_action :set_lesson
    before_action :authorize_instructor
    before_action :set_image, only: [:update, :destroy]

    def create
      @image = @lesson.images.new(image_params)
      @image.instructor_id = current_user.id  # Assign the current user's ID as instructor_id
      if @image.save
        redirect_to instructors_lesson_path(@lesson), notice: 'Image was successfully created.'
      else
        redirect_to instructors_lesson_path(@lesson)
      end
    end

    def update
      if @image.update(image_params)
        redirect_to instructors_lesson_path(@lesson), notice: 'Image was successfully updated.'
      else
        render 'instructors/lessons/show'
      end
    end

    def destroy
      @image.destroy
      redirect_to instructors_lesson_path(@lesson), notice: 'Image was successfully deleted.'
    end

    private

    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def authorize_instructor
      unless @lesson.course.instructor_id == current_user.id
        redirect_to instructors_lessons_path, alert: 'You are not authorized to perform this action.'
      end
    end

    def set_image
      @image = @lesson.images.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:value, :priority)
    end
  end
end

app/controllers/instructors/lessons_controller.rb
class Instructors::LessonsController < InstructorBaseController
  before_action :authenticate_user!
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = current_instructor.lessons
  end

  def show
    @sub_title = @lesson.sub_titles.build
    @description = @lesson.descriptions.build
    @image = @lesson.images.build
    @combined_contents = @lesson.combined_contents
  end

  def new
    @lesson = current_instructor.lessons.build
  end

  def edit
  end

  def create
    @lesson = current_instructor.lessons.build(lesson_params)

    if @lesson.save
      redirect_to instructors_lesson_path(@lesson), notice: 'Lesson was successfully created.'
    else
      flash.now[:alert] = 'There was an error creating the lesson.'
      render :new
    end
  end

  def update
    if @lesson.update(lesson_params)
      redirect_to instructors_lesson_path(@lesson), notice: 'Lesson was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating the lesson.'
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    redirect_to instructors_lessons_path, notice: 'Lesson was successfully destroyed.'
  end

  def preview
  end


  private

  def set_lesson
    @lesson = current_instructor.lessons.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :priority, :course_id)
  end
end

app/controllers/instructors/quizzes_controller.rb
class Instructors::QuizzesController < InstructorBaseController
    before_action :authenticate_user!
    before_action :set_quiz, only: [:edit, :update, :destroy]
  
    def index
      @courses = current_instructor.courses
    end
  
    def show
      @course = Course.find_by_id(params[:id])
      @quizzes = @course.quizzes
    end
  
    def new
      @quiz = current_instructor.quizzes.build
    end
  
    def edit
    end
  
    def create
      @quiz = current_instructor.quizzes.build(quiz_params)
        
      if @quiz.save
        redirect_to instructors_quiz_path(@quiz.course), notice: 'Quiz was successfully created.'
      else
        flash.now[:alert] = 'There was an error creating the quiz.'
        render :new
      end
    end
  
    def update
      if @quiz.update(quiz_params)
        redirect_to instructors_quiz_path(@quiz.course), notice: 'Quiz was successfully updated.'
      else
        flash.now[:alert] = 'There was an error updating the quiz.'
        render :edit
      end
    end
  
    def destroy
      @quiz.destroy
      redirect_to instructors_quizzes_path, notice: 'Quiz was successfully destroyed.'
    end
  
    private
  
    def set_quiz
      @quiz = current_instructor.quizzes.find(params[:id])
    end
  
    def quiz_params
      params.require(:quiz).permit(:question, :lesson_id, :answer1, :answer2, :answer3, :answer4, :right_answer, :level)
    end
  end
  

app/controllers/instructors/sub_titles_controller.rb
module Instructors
  class SubTitlesController < InstructorBaseController
    before_action :authenticate_user!
    before_action :set_lesson
    before_action :authorize_instructor
    before_action :set_sub_title, only: [:update, :destroy]

    def create
      @sub_title = @lesson.sub_titles.new(sub_title_params)
      @sub_title.instructor_id = current_user.id  # Assign the current user's ID as instructor_id
      if @sub_title.save
        redirect_to instructors_lesson_path(@lesson), notice: 'Subtitle was successfully created.'
      else
        redirect_to instructors_lesson_path(@lesson)
      end
    end

    def update
      if @sub_title.update(sub_title_params)
        redirect_to instructors_lesson_path(@lesson), notice: 'Subtitle was successfully updated.'
      else
        render 'instructors/lessons/show'
      end
    end

    def destroy
      @sub_title.destroy
      redirect_to instructors_lesson_path(@lesson), notice: 'Subtitle was successfully deleted.'
    end

    private

    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def authorize_instructor
      unless @lesson.course.instructor_id == current_user.id
        redirect_to instructors_lessons_path, alert: 'You are not authorized to perform this action.'
      end
    end

    def set_sub_title
      @sub_title = @lesson.sub_titles.find(params[:id])
    end

    def sub_title_params
      params.require(:sub_title).permit(:value, :priority)
    end
  end
end

app/controllers/learners/lessons_controller.rb
class Learners::LessonsController < LearnerBaseController
  before_action :authenticate_user!
  before_action :set_course_and_lesson, only: [:show]

  def show
    @combined_contents = @lesson.combined_contents
    set_navigation_lessons
    @lessons = Lesson.all
  end

  private

  def set_course_and_lesson
    @lesson = Lesson.find_by_id(params[:id])
    @course = @lesson.course
  end

  def set_navigation_lessons
    lessons = @course.lessons.order(priority: :asc)
    current_lesson_index = lessons.index(@lesson)
    
    @previous_lesson = lessons[current_lesson_index - 1] if current_lesson_index > 0
    @next_lesson = lessons[current_lesson_index + 1] if current_lesson_index < lessons.size - 1
  end
end

app/helpers/instructors/courses_helper.rb
module Instructors::CoursesHelper
end

app/helpers/instructors/descriptions_helper.rb
module Instructors::DescriptionsHelper
end

app/helpers/instructors/images_helper.rb
module Instructors::ImagesHelper
end

app/helpers/instructors/quizzes_helper.rb
module Instructors::QuizzesHelper
end

app/helpers/instructors/sub_titles_helper.rb
module Instructors::SubTitlesHelper
end

app/helpers/learners/lessons_helper.rb
module Learners::LessonsHelper
end

app/views/instructors/lessons/edit.html.erb
<!-- app/views/instructors/lessons/edit.html.erb -->
<div class="container mx-auto p-8">
  <div class="flex justify-between items-center mb-8">
    <div>
      <h1 class="text-4xl font-bold text-teal-600 mb-4">Edit Lesson</h1>
      <p class="text-gray-700 text-lg">Update or create new lessons with ease.</p>
    </div>
    <div>
      <%= link_to new_instructors_lesson_path, class: "bg-gradient-to-r from-teal-500 to-blue-500 hover:from-teal-600 hover:to-blue-600 text-white font-bold py-2 px-6 rounded-lg shadow-lg transition duration-300 flex items-center" do %>
        <i class="fas fa-plus-circle fa-fw text-lg mr-2"></i>
        Add Lesson
      <% end %>
    </div>
  </div>

  <hr class="my-8 border-gray-300 border-2">

  <%= render 'form' %>
</div>

app/views/instructors/lessons/index.html.erb
<div class="container mx-auto p-8">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-4xl font-bold text-teal-600">Your Lessons</h1>
    <%= link_to new_instructors_lesson_path, class: "bg-gradient-to-r from-teal-500 to-blue-500 hover:from-teal-600 hover:to-blue-600 text-white font-bold py-2 px-6 rounded-lg shadow-lg transition duration-300 flex items-center" do %>
      <i class="fas fa-plus-circle fa-fw text-lg mr-2"></i>
      Add Lesson
    <% end %>
  </div>

  <hr class="my-8 border-gray-300 border-2">

  <% if @lessons.any? %>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <% @lessons.each do |lesson| %>
        <div class="bg-white shadow-lg rounded-lg overflow-hidden transform hover:scale-105 transition duration-300 relative">
          <%= link_to instructors_lesson_path(lesson), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "absolute top-2 right-2 text-red-600 hover:text-red-800 focus:outline-none" do %>
            <i class="fas fa-times-circle fa-lg"></i>
          <% end %>

          <div class="p-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-4">
              <%= link_to lesson.title, instructors_lesson_path(lesson), class: "hover:underline" %>
            </h2>
            <p class="text-gray-600 mb-4">Priority: <%= lesson.priority %></p>
            <p class="text-gray-600">Course: <%= lesson.course.title %></p>
          </div>

          <div class="bg-gradient-to-r from-teal-500 to-blue-500 px-6 py-4 flex justify-between items-center">
            <%= link_to edit_instructors_lesson_path(lesson), class: "text-white bg-blue-600 hover:bg-blue-800 px-4 py-2 rounded focus:outline-none focus:shadow-outline transition duration-300" do %>
              <i class="fas fa-edit fa-fw mr-2"></i> Revise Lesson
            <% end %>
            <%= link_to instructors_lesson_path(lesson), class: "text-white bg-teal-600 hover:bg-teal-800 px-4 py-2 rounded focus:outline-none focus:shadow-outline transition duration-300" do %>
              <i class="fas fa-eye fa-fw mr-2"></i> View Lesson
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-700 text-center mt-12">No records found.</p>
  <% end %>
</div>

app/views/instructors/lessons/new.html.erb
<!-- app/views/instructors/lessons/new.html.erb -->
<div class="container mx-auto p-8">
  <div class="mb-8">
    <div class="flex justify-between items-center">
      <div>
        <h1 class="text-4xl font-bold text-teal-600 mb-4">New Lesson</h1>
        <p class="text-gray-700 text-lg">Create a new lesson with the details below.</p>
      </div>
      <div>
        <%= link_to instructors_lessons_path, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-6 rounded-lg shadow-lg transition duration-300 flex items-center" do %>
          <i class="fas fa-arrow-left fa-fw text-lg mr-2"></i>
          Back
        <% end %>
      </div>
    </div>
  </div>

  <hr class="my-8 border-gray-300 border-2">

  <%= render 'form' %>
</div>

app/views/instructors/lessons/show.html.erb
<!-- Main container -->
<div class="container mx-auto px-4 py-8 flex flex-wrap" data-controller='modal'>
  <!-- Left Column - Lesson Details and Content -->
  <div class="w-full lg:w-3/5 bg-white shadow-md rounded-lg overflow-hidden relative lesson-card lg:mr-8 mb-8 lg:mb-0">
    <!-- Delete Button -->
    <div class="absolute top-0 right-0 mt-4 mr-4 delete-lesson">
      <%= link_to instructors_lesson_path(@lesson), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "text-gray-400 hover:text-red-600 focus:outline-none" do %>
        <i class="fas fa-times-circle fa-lg"></i>
      <% end %>
    </div>
    
    <!-- Lesson Details -->
    <div class="p-6">
      <h1 class="text-3xl font-bold text-gray-800 mb-4"><%= @lesson.title %></h1>
      <p class="text-lg text-gray-700 mb-6">Priority: <%= @lesson.priority %></p>
      <p class="text-gray-600">Course: <%= link_to @lesson.course.title, instructors_course_path(@lesson.course), class: "text-blue-500 hover:underline" %></p>
    </div>
    
    <!-- Horizontal Rule -->
    <hr class="border-t-4 border-gray-200 my-4">
    
    <!-- Lesson Content -->
    <div class="p-6">
      <h2 class="text-2xl font-semibold text-gray-800 mb-4">Add Content to Lesson</h2>
      <div class="flex flex-wrap space-x-4">
        <button data-action="click->modal#openModal" data-modal-target="subtitle-modal" class="text-white bg-teal-500 hover:bg-teal-700 px-4 py-2 rounded focus:outline-none focus:shadow-outline flex items-center mb-4">
          <i class="fas fa-plus-circle fa-fw mr-2"></i> Subtitle
        </button>
        <button data-action="click->modal#openModal" data-modal-target="description-modal" class="text-white bg-blue-500 hover:bg-blue-700 px-4 py-2 rounded focus:outline-none focus:shadow-outline flex items-center mb-4">
          <i class="fas fa-plus-circle fa-fw mr-2"></i> Description
        </button>
        <button data-action="click->modal#openModal" data-modal-target="image-modal" class="text-white bg-indigo-500 hover:bg-indigo-700 px-4 py-2 rounded focus:outline-none focus:shadow-outline flex items-center mb-4">
          <i class="fas fa-plus-circle fa-fw mr-2"></i> Image
        </button>
      </div>
    </div>

    <!-- Action Buttons -->
    <div class="bg-gradient-to-r from-teal-500 to-blue-500 px-6 py-4 flex justify-between">
      <%= link_to edit_instructors_lesson_path(@lesson), class: "text-white bg-green-500 hover:bg-green-700 px-4 py-2 rounded focus:outline-none focus:shadow-outline flex items-center" do %>
        <i class="fas fa-edit fa-fw mr-2"></i> Revise Lesson
      <% end %>
      <%= link_to instructors_lessons_path, class: "text-white bg-gray-500 hover:bg-gray-700 px-4 py-2 rounded focus:outline-none focus:shadow-outline flex items-center" do %>
        <i class="fas fa-arrow-left fa-fw mr-2"></i> Back
      <% end %>
    </div>

    
  </div>

</div>



<div class="grid grid-cols-2 gap-4" data-controller='modal'>
  <div class="bg-white shadow-md rounded-lg">

    <% if @combined_contents.present? %>
    
      <div class="p-6">
        <h2 class="text-2xl font-semibold text-gray-800 mb-4">Combined Contents</h2>
        <% @combined_contents.each do |content| %>
          <div class="border-b border-gray-200 py-4 flex items-center justify-between">
            <% case content.class.to_s %>
              <% when 'SubTitle' %>
                <div>
                  <h3 class="text-xl font-semibold text-gray-700 mb-2">Subtitle (Priority <%= content.priority %>)</h3>
                  <p><%= content.value %></p>
                </div>
                <div class="flex items-center space-x-2">
                  <%= link_to 'javascript:void(0)', data: {'action': "click->modal#openModal", 'modal-target': "edit-subtitle-modal-#{content[:id]}"}, class: "text-gray-400 hover:text-blue-600 focus:outline-none ml-2" do %>
                    <i class="fas fa-edit fa-lg"></i> <!-- Edit Icon -->
                  <% end %>
                  <%= link_to instructors_lesson_sub_title_path(@lesson, content[:id]), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "text-gray-400 hover:text-red-600 focus:outline-none ml-2" do %>
                    <i class="fas fa-trash-alt fa-lg"></i>
                  <% end %>
                </div>
                <%= render layout: 'partials/modal', locals: { modal_id: "edit-subtitle-modal-#{content[:id]}" } do %>
                  <%= render partial: 'instructors/sub_titles/form', locals: { sub_title: content } %>
                <% end %>
              <% when 'Description' %>
                <div>
                  <h3 class="text-xl font-semibold text-gray-700 mb-2">Description (Priority <%= content[:priority] %>)</h3>
                  <p><%= content.value %></p>
                </div>
                <div class="flex items-center space-x-2">
                  <%= link_to 'javascript:void(0)', data: {'action': "click->modal#openModal", 'modal-target': "edit-description-modal-#{content[:id]}"}, class: "text-gray-400 hover:text-blue-600 focus:outline-none ml-2" do %>
                    <i class="fas fa-edit fa-lg"></i> <!-- Edit Icon -->
                  <% end %>
                  <%= link_to instructors_lesson_description_path(@lesson, content[:id]), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "text-gray-400 hover:text-red-600 focus:outline-none ml-2" do %>
                    <i class="fas fa-trash-alt fa-lg"></i>
                  <% end %>
                </div>
                <%= render layout: 'partials/modal', locals: { modal_id: "edit-description-modal-#{content[:id]}" } do %>
                  <%= render partial: 'instructors/descriptions/form', locals: { description: content } %>
                <% end %>
              <% when 'Image' %>
                <div>
                  <h3 class="text-xl font-semibold text-gray-700 mb-2">Image (Priority <%= content[:priority] %>)</h3>
                  <%= image_tag(content[:value], class: "max-w-full") %>
                </div>
                <div class="flex items-center space-x-2">
                  <%= link_to 'javascript:void(0)', data: {'action': "click->modal#openModal", 'modal-target': "edit-image-modal-#{content[:id]}"}, class: "text-gray-400 hover:text-blue-600 focus:outline-none ml-2" do %>
                    <i class="fas fa-edit fa-lg"></i> <!-- Edit Icon -->
                  <% end %>
                  <%= link_to instructors_lesson_image_path(@lesson, content[:id]), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "text-gray-400 hover:text-red-600 focus:outline-none ml-2" do %>
                    <i class="fas fa-trash-alt fa-lg"></i>
                  <% end %>
                </div>
                <%= render layout: 'partials/modal', locals: { modal_id: "edit-image-modal-#{content[:id]}" } do %>
                  <%= render partial: 'instructors/images/form', locals: { image: content } %>
                <% end %>
            <% end %>
          </div>
        <% end %>
      </div>

  <% end %>

  </div>
  <div class="bg-sky-100 p-4 rounded-lg border border-gray-300 shadow-lg">
    <h2 class="text-2xl font-semibold text-gray-800 mb-4">Lesson Preview</h2>
    <hr>
    <div class="my-4">
      <h3 class="text-lg font-semibold text-gray-700 my-4"><%= @lesson.title %></h3>
      <% @combined_contents.each do |content| %>
        <% case content.class.to_s %>
          <% when 'SubTitle' %>
            <h4 class="text-lg font-bold text-gray-900 my-4"><%= content[:value] %></h4>
          <% when 'Description' %>
            <div class="text-base text-gray-700 italic my-4"><%= content.value %></div>
          <% when 'Image' %>
            <div class="flex justify-center">
              <%= image_tag(content[:value], class: "max-w-full rounded-lg shadow-md") %>
            </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= render layout: 'partials/modal', locals: { modal_id: 'subtitle-modal' } do %>
  <%= render partial: 'instructors/sub_titles/form', locals: { sub_title: @sub_title } %>
<% end %>

<%= render layout: 'partials/modal', locals: { modal_id: 'description-modal' } do %>
  <%= render partial: 'instructors/descriptions/form', locals: {description: @description} %>
<% end %>

<%= render layout: 'partials/modal', locals: { modal_id: 'image-modal' } do %>
  <%= render partial: 'instructors/images/form', locals: {image: @image} %>
<% end %>