config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }

  namespace :learners do
    resources :dashboard, only: [:index]
    resources :courses, only: [:show, :index]
    resources :lessons, only: [:show]
    resources :quizzes, only: [:show, :index] do
      collection do
        get 'level', to: 'quizzes#level'
        post '/:id', to: 'quizzes#submit_quiz_answer', as: 'submit_quiz_answer'
      end
    end
  end

  namespace :instructors do
    resources :dashboard, only: [:index]
    resources :courses
    resources :lessons do
      resources :sub_titles, only: [:create, :destroy, :update]
      resources :images, only: [:create, :destroy, :update]
      resources :descriptions, only: [:create, :destroy, :update]
    end
    resources :quizzes
    resources :blogs
  end

  # Define API routes for blogs
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :blogs, only: [:index, :show]
      # Add more API endpoints as needed
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :lesson
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :instructor, class_name: 'User'

  validates :description, presence: true
  validates :title, presence: true, uniqueness: { scope: :instructor_id }
  validates :instructor_id, presence: true

  has_rich_text :description

  def trix_description
    description.body.to_s if description.present?
  end
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :instructor, class_name: 'User'
  has_many :lessons, dependent: :destroy
  has_many :users
  has_many :quizzes, through: :lessons

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :instructor_id, presence: true
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :lesson
  belongs_to :instructor, class_name: 'User', foreign_key: 'instructor_id'

  has_rich_text :value
  
  # Validations
  validates :value, presence: true
  validates :priority, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :lesson_id, presence: true
  validates :instructor_id, presence: true

  def upcoming_priority
    lesson.combined_contents.collect(&:priority).max.to_i + 1
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/image.rb
# app/models/image.rb
class Image < ApplicationRecord
    belongs_to :lesson
    belongs_to :instructor, class_name: 'User', foreign_key: 'instructor_id'
  
    # Validations
    validates :value, presence: true
    validates :priority, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
    validates :lesson_id, presence: true
    validates :instructor_id, presence: true

    def upcoming_priority
        lesson.combined_contents.collect(&:priority).max.to_i + 1 
    end
end
  

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  belongs_to :instructor, class_name: 'User'
  has_many :sub_titles, -> { order(:priority) }, dependent: :destroy
  has_many :descriptions, -> { order(:priority) }, dependent: :destroy
  has_many :images, -> { order(:priority) }, dependent: :destroy
  has_many :quiz, dependent: :destroy

  validates :course_id, presence: true
  validates :title, presence: true, uniqueness: { scope: :course_id }
  validates :priority, presence: true, numericality: { only_integer: true, greater_than: 0 }, uniqueness: { scope: :course_id }
  validates :instructor_id, presence: true

  validate :priority_must_be_unique_within_course

  def combined_contents
    combined = []

    # Fetch all subtitles, descriptions, and images associated with this lesson
    subtitles = sub_titles.to_a.select(&:persisted?)
    descriptions = self.descriptions.to_a.select(&:persisted?)
    images = self.images.to_a.select(&:persisted?)

    combined += subtitles
    combined += descriptions
    combined += images

    # Sort combined array by priority
    combined.sort_by! { |item| item.priority }

    combined
  end

  private

  def priority_must_be_unique_within_course
    if course.lessons.where(priority: priority).exists? && (new_record? || changed.include?('priority'))
      errors.add(:priority, "must be unique within the course")
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
# app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :lesson
  validates :lesson_id, presence: true
  has_one :course, through: :lesson
  

  def self.check_answer(params)
    @feedback = {}
    params['quiz_ids'].each do |quiz|
      quiz_id = Quiz.find_by_id(quiz)
      if params['quiz_answers'][quiz] == quiz_id.right_answer
        return true
      else false
      end
    end
  end
end

app/models/sub_title.rb
class SubTitle < ApplicationRecord
    belongs_to :lesson
    belongs_to :instructor, class_name: 'User', foreign_key: 'instructor_id'  # Assuming instructor_id is a foreign key in sub_titles table

    validates :value, presence: true
    validates :priority, numericality: { only_integer: true }
    validates :instructor_id, presence: true

    def upcoming_priority
        lesson.combined_contents.collect(&:priority).max.to_i + 1  
    end
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :assignment
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :courses, foreign_key: :instructor_id, dependent: :destroy
  has_many :lessons, foreign_key: :instructor_id, dependent: :destroy
  has_many :blogs, foreign_key: :instructor_id, dependent: :destroy
  has_many :quizzes, foreign_key: :instructor_id, dependent: :destroy
  serialize :role, JSON

  # Ensure the role column contains an array
  before_save :ensure_role_is_array

  private

  def ensure_role_is_array
    self.role = [] if self.role.nil?
  end
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def after_sign_in_path_for(resource)
    session[:login_as] = params[:login_as]
    case session[:login_as]
    when 'learner'
      learners_dashboard_index_path
    when 'instructor'
      instructors_dashboard_index_path
    else
      learners_dashboard_index_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/instructor_base_controller.rb
class InstructorBaseController < ApplicationController
  layout 'instructors'
  before_action :authenticate_user!
  before_action :ensure_instructor
  before_action :current_instructor

  private

  def current_instructor
    @current_instructor = current_user
  end

  def ensure_instructor
    unless session[:login_as] == 'instructor'
      flash[:alert] = "You are not authorized to access this page."
      redirect_to learners_dashboard_index_path # or any other path you want to redirect to
    end
  end
end

app/controllers/learner_base_controller.rb
class LearnerBaseController < ApplicationController
  layout 'learners'
  before_action :authenticate_user!
  before_action :ensure_learner
  before_action :current_learner

  private

  def current_learner
    @current_learner = current_user
  end

  def ensure_learner
    unless session[:login_as] == 'learner'
      flash[:alert] = "You are not authorized to access this page."
      redirect_to instructors_dashboard_index_path # or any other path you want to redirect to
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructors/images_helper.rb
module Instructors::ImagesHelper
end

app/helpers/learners/lessons_helper.rb
module Learners::LessonsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/partials/_instructor_flash_messages.html.erb
<% flash.each do |type, message| %>
    <% next unless message.is_a?(String) %>
    <% css_class, icon_color, bg_color = case type.to_sym
       when :notice
         ["text-green-800", "text-green-500", "bg-green-50"]
       when :alert, :error
         ["text-red-800", "text-red-500", "bg-red-50"]
       else
         ["text-blue-800", "text-blue-500", "bg-blue-50"]
       end
    %>
    <div id="alert-<%= type %>" data-controller="alert" data-alert-target="dismissable" class="flex items-center p-4 mb-4 <%= css_class %> rounded-lg <%= bg_color %> dark:bg-gray-800 dark:<%= icon_color %>" role="alert">
      <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
      </svg>
      <span class="sr-only">Info</span>
      <div class="ms-3 text-sm font-medium">
        <%= message.html_safe %> <!-- Allow HTML links in flash messages -->
      </div>
      <button type="button" data-action="click->alert#dismiss" class="ms-auto -mx-1.5 -my-1.5 <%= bg_color %> <%= icon_color %> rounded-lg focus:ring-2 focus:ring-<%= type %>-400 p-1.5 hover:<%= bg_color.dasherize %>-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:<%= icon_color %> dark:hover:bg-gray-700" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
      </button>
    </div>
<% end %>
  

app/views/partials/_instructor_footer.html.erb
<footer class="bg-gradient-to-r from-blue-600 to-teal-600 text-white text-center py-4">
  <p>&copy; <%= Time.now.year %> Instructor Portal. All rights reserved.</p>
</footer>

app/views/partials/_instructor_header.html.erb
<header class="bg-gradient-to-r from-blue-500 to-teal-500 text-white p-4 shadow-lg">
  <div class="container mx-auto">
    <h1 class="text-3xl font-bold">Instructor Portal</h1>
  </div>
</header>

app/views/partials/_instructor_side_nav.html.erb
<nav class="w-full lg:w-64 bg-gradient-to-r from-teal-500 to-blue-500 shadow-lg text-white">
  <div class="p-4">
    <ul>
      <li>
        <%= link_to instructors_dashboard_index_path, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-tachometer-alt fa-fw text-white mr-2"></i>
          Dashboard
        <% end %>
      </li>
      <li>
        <%= link_to instructors_courses_path, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-book fa-fw text-white mr-2"></i>
          Courses
        <% end %>
      </li>
      <li>
        <%= link_to instructors_lessons_path, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-chalkboard-teacher fa-fw text-white mr-2"></i>
          Lessons
        <% end %>
      </li>
      <li>
        <%= link_to instructors_quizzes_path, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-question-circle fa-fw text-white mr-2"></i>
          Quizzes
        <% end %>
      </li>
      <li>
        <%= link_to instructors_blogs_path, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-blog fa-fw text-white mr-2"></i> <!-- Set specific icon for Blogs -->
          Blogs
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-sign-out-alt fa-fw text-white mr-2"></i>
          Logout
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/partials/_learner_flash_messages.html.erb
<% flash.each do |type, message| %>
    <% next unless message.is_a?(String) %>
    <% css_class, icon_color, bg_color = case type.to_sym
       when :notice
         ["text-green-800", "text-green-500", "bg-green-50"]
       when :alert, :error
         ["text-red-800", "text-red-500", "bg-red-50"]
       else
         ["text-blue-800", "text-blue-500", "bg-blue-50"]
       end
    %>
    <div id="alert-<%= type %>" data-controller="alert" data-alert-target="dismissable" class="flex items-center p-4 mb-4 <%= css_class %> rounded-lg <%= bg_color %> dark:bg-gray-800 dark:<%= icon_color %>" role="alert">
      <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
      </svg>
      <span class="sr-only">Info</span>
      <div class="ms-3 text-sm font-medium">
        <%= message.html_safe %> <!-- Allow HTML links in flash messages -->
      </div>
      <button type="button" data-action="click->alert#dismiss" class="ms-auto -mx-1.5 -my-1.5 <%= bg_color %> <%= icon_color %> rounded-lg focus:ring-2 focus:ring-<%= type %>-400 p-1.5 hover:<%= bg_color.dasherize %>-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:<%= icon_color %> dark:hover:bg-gray-700" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
      </button>
    </div>
  <% end %>
  

app/views/partials/_learner_footer.html.erb
<footer class="bg-gradient-to-r from-cyan-600 to-sky-600 text-white text-center py-4">
  <p>&copy; <%= Time.now.year %> Learner Portal. All rights reserved.</p>
</footer>

app/views/partials/_learner_header.html.erb
<header class="bg-gradient-to-r from-sky-500 to-cyan-500 text-white p-4 shadow-lg">
  <div class="container mx-auto">
    <h1 class="text-3xl font-bold">Learner Portal</h1>
  </div>
</header>

app/views/partials/_learner_side_nav.html.erb
<nav class="w-full lg:w-64 bg-gradient-to-r from-cyan-500 to-sky-500 shadow-lg text-white">
  <div class="p-4">
    <ul>
      <li>
        <%= link_to learners_dashboard_index_path, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-tachometer-alt fa-fw text-white mr-2"></i>
          Dashboard
        <% end %>
      </li>
      <li>
        <%= link_to learners_courses_path, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-book fa-fw text-white mr-2"></i>
          Courses
        <% end %>
      </li>
      <li>
        <%= link_to learners_quizzes_path, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-question-circle fa-fw text-white mr-2"></i>
          Quizzes
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "flex items-center py-2 px-4 rounded-lg text-lg font-bold hover:border hover:border-black hover:shadow-lg" do %>
          <i class="fas fa-sign-out-alt fa-fw text-white mr-2"></i>
          Logout
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/partials/_modal.html.erb
<div id="<%= modal_id %>" class="modal hidden fixed z-50 inset-0 overflow-y-auto bg-gray-800 bg-opacity-50 backdrop-blur-sm flex items-center justify-center" data-controller='modal'>
  <div class="bg-white rounded-lg shadow-lg w-11/12 md:w-3/4 lg:w-2/3 xl:w-1/2 max-h-screen p-6 overflow-auto">
    <div class="flex justify-end">
      <button data-action="click->modal#closeModal" data-modal-target="<%= modal_id %>" class="text-gray-400 hover:text-red-600 focus:outline-none">
        <i class="fas fa-times-circle fa-lg"></i>
      </button>
    </div>
    <%= yield %>
  </div>
</div>