config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }

  namespace :learners do
    resources :dashboard, only: [:index]
    resources :courses, only: [:show, :index]
    resources :lessons, only: [:show]
    resources :quizzes, only: [:show, :index] do
      collection do
        get 'level', to: 'quizzes#level'
        post '/:id', to: 'quizzes#submit_quiz_answer', as: 'submit_quiz_answer'
      end
    end
  end

  namespace :instructors do
    resources :dashboard, only: [:index]
    resources :courses
    resources :lessons do
      resources :sub_titles, only: [:create, :destroy, :update]
      resources :images, only: [:create, :destroy, :update]
      resources :descriptions, only: [:create, :destroy, :update]
    end
    resources :quizzes
    resources :blogs
  end

  # Define API routes for blogs
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :blogs, only: [:index, :show]
      # Add more API endpoints as needed
    end
  end

end

app/controllers/instructors/courses_controller.rb
# app/controllers/instructors/courses_controller.rb
class Instructors::CoursesController < InstructorBaseController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = current_instructor.courses
  end

  def show
  end

  def new
    @course = current_instructor.courses.build
  end

  def edit
  end

  def create
    @course = current_instructor.courses.build(course_params)

    if @course.save
      redirect_to instructors_course_path(@course), notice: 'Course was successfully created.'
    else
      flash.now[:alert] = 'There was an error creating the course.'
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to instructors_course_path(@course), notice: 'Course was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating the course.'
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to instructors_courses_path, notice: 'Course was successfully destroyed.'
  end

  private

  def set_course
    @course = current_instructor.courses.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description)
  end
end

  

app/controllers/learners/courses_controller.rb
class Learners::CoursesController < LearnerBaseController
    before_action :authenticate_user!

    def index
        @courses = Course.all
    end

    def show
        @course = Course.find_by_id(params[:id])
    end
end

app/controllers/learners/dashboard_controller.rb
class Learners::DashboardController < LearnerBaseController
  before_action :authenticate_user!

  def index
  end
  
end

  

app/controllers/learners/lessons_controller.rb
class Learners::LessonsController < LearnerBaseController
  before_action :authenticate_user!
  before_action :set_course_and_lesson, only: [:show]

  def show
    @combined_contents = @lesson.combined_contents
    set_navigation_lessons
    @lessons = Lesson.all
  end

  private

  def set_course_and_lesson
    @lesson = Lesson.find_by_id(params[:id])
    @course = @lesson.course
  end

  def set_navigation_lessons
    lessons = @course.lessons.order(priority: :asc)
    current_lesson_index = lessons.index(@lesson)
    
    @previous_lesson = lessons[current_lesson_index - 1] if current_lesson_index > 0
    @next_lesson = lessons[current_lesson_index + 1] if current_lesson_index < lessons.size - 1
  end
end

app/controllers/learners/quizzes_controller.rb
class Learners::QuizzesController < LearnerBaseController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :level, :submit_quiz_answer]
  before_action :set_quizzes, only: :submit_quiz_answer

  def index
    @courses = Course.all
  end

  def show
    if params[:level].present?
      @quizzes = @course.quizzes.where(level: params[:level]).shuffle
      @quiz_results = {}
    end
  end

  def level; end

  def submit_quiz_answer
    if missing_answers?
      set_flash_alert_and_redirect
      return
    end

    process_quiz_answers
    calculate_quiz_summary

    render :show
  end

  private

  def set_course
    @course = Course.find(params[:id] || params[:course_id])
  end

  def set_quizzes
    @quizzes = Quiz.find(params[:quiz_ids])
  end

  def missing_answers?
    !params[:quiz_answers] || @quizzes.count != params[:quiz_answers].keys.count
  end

  def set_flash_alert_and_redirect
    flash[:alert] = "Please answer all questions."
    redirect_to learners_quiz_path(@course.id, level: params[:level])
  end

  def process_quiz_answers
    @quiz_results = {}
    @correct_count = 0

    @quizzes.each do |quiz|
      user_answer = params[:quiz_answers][quiz.id.to_s]
      correct_answer = quiz.right_answer

      if correct_answer == user_answer
        @quiz_results[quiz.id.to_s] = [true, "Right Answer", user_answer]
        @correct_count += 1
      else
        @quiz_results[quiz.id.to_s] = [false, "Wrong Answer, Right is #{correct_answer}", user_answer]
      end
    end
  end

  def calculate_quiz_summary
    total_questions = @quizzes.size
    wrong_count = total_questions - @correct_count
    percentage = (@correct_count.to_f / total_questions * 100).round(2)

    @quiz_summary = {
      total_questions: total_questions,
      correct_count: @correct_count,
      wrong_count: wrong_count,
      percentage: percentage
    }
  end
end

app/helpers/instructors/courses_helper.rb
module Instructors::CoursesHelper
end

app/helpers/learners/lessons_helper.rb
module Learners::LessonsHelper
end

app/views/learners/courses/index.html.erb
<div class="container mx-auto p-8">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-4xl font-bold text-teal-600">Your Courses</h1>
  </div>
  <hr class="my-8 border-gray-300 border-2">
  <% if @courses.any? %>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <% @courses.each do |course| %>
        <div class="bg-white shadow-lg rounded-lg overflow-hidden transform hover:scale-105 transition duration-300 flex flex-col">
          <div class="flex justify-between items-center px-4 pt-4">
            <h2 class="text-2xl font-bold text-gray-800"><%= link_to course.title, instructors_course_path(course), class: "hover:underline" %></h2>
            <%= link_to learners_course_path(course), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "text-gray-400 hover:text-red-600 focus:outline-none" do %>
              <i class="fas fa-times-circle fa-lg"></i>
            <% end %>
          </div>
          <div class="p-6 flex-1">
            <p class="text-gray-600 mb-4"><%= course.description.truncate(150) %></p>
          </div>
          <div class="bg-gradient-to-r from-teal-500 to-blue-500 px-6 py-4 flex justify-between items-center">
            <%= link_to learners_course_path(course), class: "text-white bg-green-700 hover:bg-green-900 px-4 py-2 rounded focus:outline-none focus:shadow-outline transition duration-300" do %>
              <i class="fas fa-eye fa-fw mr-2"></i> Checkout Lessons
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-700 text-center mt-12">No records found.</p>
  <% end %>
</div>

app/views/learners/courses/show.html.erb
<div class="container mx-auto px-4 py-8">
  <div class="max-w-3xl bg-white shadow-md rounded-lg overflow-hidden">
    <div class="flex justify-between items-center px-6 py-4">
      <h1 class="text-3xl font-bold text-gray-800"><%= @course.title %></h1>
      <%= link_to learners_course_path(@course), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "text-gray-400 hover:text-red-600 focus:outline-none" do %>
        <i class="fas fa-times-circle fa-lg"></i>
      <% end %>
    </div>

    <div class="p-6">
      <p class="text-lg text-gray-700 mb-6"><%= @course.description %></p>

      <hr class="my-8 border-gray-300 border-t-2">

      <h2 class="text-2xl font-bold text-gray-800 mb-4">Lessons</h2>
      <% if @course.lessons.any? %>
        <div class="grid grid-cols-1 gap-4">
          <% @course.lessons.order(priority: :asc).each do |lesson| %>
            <div class="bg-gray-100 rounded-lg shadow-md p-4">
              <%= link_to lesson.title, learners_lesson_path(lesson), class: "text-blue-500 hover:underline text-lg font-semibold" %>
            </div>
          <% end %>
        </div>
      <% else %>
        <p class="text-gray-600 mb-6">No lessons available for this course.</p>
      <% end %>

      <div class="mt-8 flex justify-between">
        <%= link_to learners_courses_path, class: "flex items-center border text-gray-700 text-sm font-bold py-2 px-4 rounded hover:bg-gray-200 focus:outline-none focus:shadow-outline" do %>
          <i class="fas fa-arrow-left fa-fw mr-2"></i> Back
        <% end %>
      </div>
    </div>
  </div>
</div>